let shopItemsData = [
  {
    id: "qwertyui",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "opasdfg",
    name: "Casual Shirt",
    price: 30,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "hjklzxc",
    name: "Casual Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "vbnmmqw",
    name: "Casual Shirt",
    price: 75,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "mnbvcx",
    name: "Casual Shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "zlkjhg",
    name: "Casual Shirt",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "fdsapoi",
    name: "Casual Shirt",
    price: 220,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "uytrewq",
    name: "Casual Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "poiuyt",
    name: "Casual Shirt",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "rewqlk",
    name: "Casual Shirt",
    price: 330,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "jhgfdsa",
    name: "Casual Shirt",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
  {
    id: "mnbvcxz",
    name: "Casual Shirt",
    price: 75,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/7.jpg",
  },
];
